#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync_SAP_STATUS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WolfApproveCore.eco3-trial")]
	public partial class SingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTRNMemo(TRNMemo instance);
    partial void UpdateTRNMemo(TRNMemo instance);
    partial void DeleteTRNMemo(TRNMemo instance);
    #endregion
		
		public SingDataContext() : 
				base(global::Sync_SAP_STATUS.Properties.Settings.Default.WolfApproveCore_eco3_trialConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TRNMemo> TRNMemos
		{
			get
			{
				return this.GetTable<TRNMemo>();
			}
		}
		
		public System.Data.Linq.Table<MSTTemplate> MSTTemplates
		{
			get
			{
				return this.GetTable<MSTTemplate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRNMemo")]
	public partial class TRNMemo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MemoId;
		
		private string _DocumentNo;
		
		private System.Nullable<int> _TemplateId;
		
		private string _GroupTemplateName;
		
		private string _TemplateName;
		
		private string _TemplateType;
		
		private System.Nullable<int> _DepartmentId;
		
		private string _DocumentCode;
		
		private System.Nullable<bool> _IsPublic;
		
		private string _ReportLang;
		
		private string _TemplateDetail;
		
		private string _ToPerson;
		
		private string _CcPerson;
		
		private string _TemplateSubject;
		
		private string _TTextForm;
		
		private string _TAdvanceForm;
		
		private System.Nullable<bool> _AutoApprove;
		
		private string _AutoApproveWhen;
		
		private System.Nullable<bool> _ApproverCanEdit;
		
		private System.Nullable<int> _CreatorId;
		
		private string _CNameTh;
		
		private string _CNameEn;
		
		private System.Nullable<int> _CPositionId;
		
		private string _CPositionTh;
		
		private string _CPositionEn;
		
		private System.Nullable<int> _CDepartmentId;
		
		private string _CDepartmentTh;
		
		private string _CDepartmentEn;
		
		private System.Nullable<int> _CDivisionId;
		
		private string _CDivisionTh;
		
		private string _CDivisionEn;
		
		private System.Nullable<int> _RequesterId;
		
		private string _RNameTh;
		
		private string _RNameEn;
		
		private System.Nullable<int> _RPositionId;
		
		private string _RPositionTh;
		
		private string _RPositionEn;
		
		private System.Nullable<int> _RDepartmentId;
		
		private string _RDepartmentTh;
		
		private string _RDepartmentEn;
		
		private System.Nullable<int> _RDivisionId;
		
		private string _RDivisionTh;
		
		private string _RDivisionEn;
		
		private string _MemoSubject;
		
		private string _MTextForm;
		
		private string _MAdvancveForm;
		
		private System.Nullable<int> _StatusId;
		
		private string _StatusName;
		
		private System.Nullable<int> _CurrentApprovalLevel;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<System.DateTime> _RequestDate;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private string _ModifiedBy;
		
		private string _LastActionBy;
		
		private System.Nullable<int> _LastStatusId;
		
		private string _LastStatusName;
		
		private System.Nullable<int> _PersonWaitingId;
		
		private string _PersonWaiting;
		
		private System.Nullable<int> _AccountId;
		
		private System.Nullable<int> _CompanyId;
		
		private string _CompanyName;
		
		private System.Nullable<int> _ProjectID;
		
		private string _ProjectName;
		
		private bool _IsReaded;
		
		private string _TemplateApproveId;
		
		private System.Nullable<int> _CheckEmpID;
		
		private System.Nullable<System.DateTime> _SLAStartDate;
		
		private System.Nullable<System.DateTime> _SLACompletedDate;
		
		private System.Nullable<System.DateTime> _CompletedDate;
		
		private System.Nullable<bool> _IsProcess;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemoIdChanging(int value);
    partial void OnMemoIdChanged();
    partial void OnDocumentNoChanging(string value);
    partial void OnDocumentNoChanged();
    partial void OnTemplateIdChanging(System.Nullable<int> value);
    partial void OnTemplateIdChanged();
    partial void OnGroupTemplateNameChanging(string value);
    partial void OnGroupTemplateNameChanged();
    partial void OnTemplateNameChanging(string value);
    partial void OnTemplateNameChanged();
    partial void OnTemplateTypeChanging(string value);
    partial void OnTemplateTypeChanged();
    partial void OnDepartmentIdChanging(System.Nullable<int> value);
    partial void OnDepartmentIdChanged();
    partial void OnDocumentCodeChanging(string value);
    partial void OnDocumentCodeChanged();
    partial void OnIsPublicChanging(System.Nullable<bool> value);
    partial void OnIsPublicChanged();
    partial void OnReportLangChanging(string value);
    partial void OnReportLangChanged();
    partial void OnTemplateDetailChanging(string value);
    partial void OnTemplateDetailChanged();
    partial void OnToPersonChanging(string value);
    partial void OnToPersonChanged();
    partial void OnCcPersonChanging(string value);
    partial void OnCcPersonChanged();
    partial void OnTemplateSubjectChanging(string value);
    partial void OnTemplateSubjectChanged();
    partial void OnTTextFormChanging(string value);
    partial void OnTTextFormChanged();
    partial void OnTAdvanceFormChanging(string value);
    partial void OnTAdvanceFormChanged();
    partial void OnAutoApproveChanging(System.Nullable<bool> value);
    partial void OnAutoApproveChanged();
    partial void OnAutoApproveWhenChanging(string value);
    partial void OnAutoApproveWhenChanged();
    partial void OnApproverCanEditChanging(System.Nullable<bool> value);
    partial void OnApproverCanEditChanged();
    partial void OnCreatorIdChanging(System.Nullable<int> value);
    partial void OnCreatorIdChanged();
    partial void OnCNameThChanging(string value);
    partial void OnCNameThChanged();
    partial void OnCNameEnChanging(string value);
    partial void OnCNameEnChanged();
    partial void OnCPositionIdChanging(System.Nullable<int> value);
    partial void OnCPositionIdChanged();
    partial void OnCPositionThChanging(string value);
    partial void OnCPositionThChanged();
    partial void OnCPositionEnChanging(string value);
    partial void OnCPositionEnChanged();
    partial void OnCDepartmentIdChanging(System.Nullable<int> value);
    partial void OnCDepartmentIdChanged();
    partial void OnCDepartmentThChanging(string value);
    partial void OnCDepartmentThChanged();
    partial void OnCDepartmentEnChanging(string value);
    partial void OnCDepartmentEnChanged();
    partial void OnCDivisionIdChanging(System.Nullable<int> value);
    partial void OnCDivisionIdChanged();
    partial void OnCDivisionThChanging(string value);
    partial void OnCDivisionThChanged();
    partial void OnCDivisionEnChanging(string value);
    partial void OnCDivisionEnChanged();
    partial void OnRequesterIdChanging(System.Nullable<int> value);
    partial void OnRequesterIdChanged();
    partial void OnRNameThChanging(string value);
    partial void OnRNameThChanged();
    partial void OnRNameEnChanging(string value);
    partial void OnRNameEnChanged();
    partial void OnRPositionIdChanging(System.Nullable<int> value);
    partial void OnRPositionIdChanged();
    partial void OnRPositionThChanging(string value);
    partial void OnRPositionThChanged();
    partial void OnRPositionEnChanging(string value);
    partial void OnRPositionEnChanged();
    partial void OnRDepartmentIdChanging(System.Nullable<int> value);
    partial void OnRDepartmentIdChanged();
    partial void OnRDepartmentThChanging(string value);
    partial void OnRDepartmentThChanged();
    partial void OnRDepartmentEnChanging(string value);
    partial void OnRDepartmentEnChanged();
    partial void OnRDivisionIdChanging(System.Nullable<int> value);
    partial void OnRDivisionIdChanged();
    partial void OnRDivisionThChanging(string value);
    partial void OnRDivisionThChanged();
    partial void OnRDivisionEnChanging(string value);
    partial void OnRDivisionEnChanged();
    partial void OnMemoSubjectChanging(string value);
    partial void OnMemoSubjectChanged();
    partial void OnMTextFormChanging(string value);
    partial void OnMTextFormChanged();
    partial void OnMAdvancveFormChanging(string value);
    partial void OnMAdvancveFormChanged();
    partial void OnStatusIdChanging(System.Nullable<int> value);
    partial void OnStatusIdChanged();
    partial void OnStatusNameChanging(string value);
    partial void OnStatusNameChanged();
    partial void OnCurrentApprovalLevelChanging(System.Nullable<int> value);
    partial void OnCurrentApprovalLevelChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnRequestDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestDateChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnLastActionByChanging(string value);
    partial void OnLastActionByChanged();
    partial void OnLastStatusIdChanging(System.Nullable<int> value);
    partial void OnLastStatusIdChanged();
    partial void OnLastStatusNameChanging(string value);
    partial void OnLastStatusNameChanged();
    partial void OnPersonWaitingIdChanging(System.Nullable<int> value);
    partial void OnPersonWaitingIdChanged();
    partial void OnPersonWaitingChanging(string value);
    partial void OnPersonWaitingChanged();
    partial void OnAccountIdChanging(System.Nullable<int> value);
    partial void OnAccountIdChanged();
    partial void OnCompanyIdChanging(System.Nullable<int> value);
    partial void OnCompanyIdChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnProjectIDChanging(System.Nullable<int> value);
    partial void OnProjectIDChanged();
    partial void OnProjectNameChanging(string value);
    partial void OnProjectNameChanged();
    partial void OnIsReadedChanging(bool value);
    partial void OnIsReadedChanged();
    partial void OnTemplateApproveIdChanging(string value);
    partial void OnTemplateApproveIdChanged();
    partial void OnCheckEmpIDChanging(System.Nullable<int> value);
    partial void OnCheckEmpIDChanged();
    partial void OnSLAStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSLAStartDateChanged();
    partial void OnSLACompletedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSLACompletedDateChanged();
    partial void OnCompletedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCompletedDateChanged();
    partial void OnIsProcessChanging(System.Nullable<bool> value);
    partial void OnIsProcessChanged();
    #endregion
		
		public TRNMemo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemoId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MemoId
		{
			get
			{
				return this._MemoId;
			}
			set
			{
				if ((this._MemoId != value))
				{
					this.OnMemoIdChanging(value);
					this.SendPropertyChanging();
					this._MemoId = value;
					this.SendPropertyChanged("MemoId");
					this.OnMemoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentNo", DbType="NVarChar(50)")]
		public string DocumentNo
		{
			get
			{
				return this._DocumentNo;
			}
			set
			{
				if ((this._DocumentNo != value))
				{
					this.OnDocumentNoChanging(value);
					this.SendPropertyChanging();
					this._DocumentNo = value;
					this.SendPropertyChanged("DocumentNo");
					this.OnDocumentNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", DbType="Int")]
		public System.Nullable<int> TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					this.OnTemplateIdChanging(value);
					this.SendPropertyChanging();
					this._TemplateId = value;
					this.SendPropertyChanged("TemplateId");
					this.OnTemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupTemplateName", DbType="NVarChar(500)")]
		public string GroupTemplateName
		{
			get
			{
				return this._GroupTemplateName;
			}
			set
			{
				if ((this._GroupTemplateName != value))
				{
					this.OnGroupTemplateNameChanging(value);
					this.SendPropertyChanging();
					this._GroupTemplateName = value;
					this.SendPropertyChanged("GroupTemplateName");
					this.OnGroupTemplateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateName", DbType="NVarChar(500)")]
		public string TemplateName
		{
			get
			{
				return this._TemplateName;
			}
			set
			{
				if ((this._TemplateName != value))
				{
					this.OnTemplateNameChanging(value);
					this.SendPropertyChanging();
					this._TemplateName = value;
					this.SendPropertyChanged("TemplateName");
					this.OnTemplateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateType", DbType="NVarChar(100)")]
		public string TemplateType
		{
			get
			{
				return this._TemplateType;
			}
			set
			{
				if ((this._TemplateType != value))
				{
					this.OnTemplateTypeChanging(value);
					this.SendPropertyChanging();
					this._TemplateType = value;
					this.SendPropertyChanged("TemplateType");
					this.OnTemplateTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="Int")]
		public System.Nullable<int> DepartmentId
		{
			get
			{
				return this._DepartmentId;
			}
			set
			{
				if ((this._DepartmentId != value))
				{
					this.OnDepartmentIdChanging(value);
					this.SendPropertyChanging();
					this._DepartmentId = value;
					this.SendPropertyChanged("DepartmentId");
					this.OnDepartmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentCode", DbType="NVarChar(50)")]
		public string DocumentCode
		{
			get
			{
				return this._DocumentCode;
			}
			set
			{
				if ((this._DocumentCode != value))
				{
					this.OnDocumentCodeChanging(value);
					this.SendPropertyChanging();
					this._DocumentCode = value;
					this.SendPropertyChanged("DocumentCode");
					this.OnDocumentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublic", DbType="Bit")]
		public System.Nullable<bool> IsPublic
		{
			get
			{
				return this._IsPublic;
			}
			set
			{
				if ((this._IsPublic != value))
				{
					this.OnIsPublicChanging(value);
					this.SendPropertyChanging();
					this._IsPublic = value;
					this.SendPropertyChanged("IsPublic");
					this.OnIsPublicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportLang", DbType="NVarChar(2)")]
		public string ReportLang
		{
			get
			{
				return this._ReportLang;
			}
			set
			{
				if ((this._ReportLang != value))
				{
					this.OnReportLangChanging(value);
					this.SendPropertyChanging();
					this._ReportLang = value;
					this.SendPropertyChanged("ReportLang");
					this.OnReportLangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateDetail", DbType="NVarChar(500)")]
		public string TemplateDetail
		{
			get
			{
				return this._TemplateDetail;
			}
			set
			{
				if ((this._TemplateDetail != value))
				{
					this.OnTemplateDetailChanging(value);
					this.SendPropertyChanging();
					this._TemplateDetail = value;
					this.SendPropertyChanged("TemplateDetail");
					this.OnTemplateDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToPerson", DbType="NVarChar(MAX)")]
		public string ToPerson
		{
			get
			{
				return this._ToPerson;
			}
			set
			{
				if ((this._ToPerson != value))
				{
					this.OnToPersonChanging(value);
					this.SendPropertyChanging();
					this._ToPerson = value;
					this.SendPropertyChanged("ToPerson");
					this.OnToPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CcPerson", DbType="NVarChar(MAX)")]
		public string CcPerson
		{
			get
			{
				return this._CcPerson;
			}
			set
			{
				if ((this._CcPerson != value))
				{
					this.OnCcPersonChanging(value);
					this.SendPropertyChanging();
					this._CcPerson = value;
					this.SendPropertyChanged("CcPerson");
					this.OnCcPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateSubject", DbType="NVarChar(500)")]
		public string TemplateSubject
		{
			get
			{
				return this._TemplateSubject;
			}
			set
			{
				if ((this._TemplateSubject != value))
				{
					this.OnTemplateSubjectChanging(value);
					this.SendPropertyChanging();
					this._TemplateSubject = value;
					this.SendPropertyChanged("TemplateSubject");
					this.OnTemplateSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTextForm", DbType="NVarChar(MAX)")]
		public string TTextForm
		{
			get
			{
				return this._TTextForm;
			}
			set
			{
				if ((this._TTextForm != value))
				{
					this.OnTTextFormChanging(value);
					this.SendPropertyChanging();
					this._TTextForm = value;
					this.SendPropertyChanged("TTextForm");
					this.OnTTextFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAdvanceForm", DbType="NVarChar(MAX)")]
		public string TAdvanceForm
		{
			get
			{
				return this._TAdvanceForm;
			}
			set
			{
				if ((this._TAdvanceForm != value))
				{
					this.OnTAdvanceFormChanging(value);
					this.SendPropertyChanging();
					this._TAdvanceForm = value;
					this.SendPropertyChanged("TAdvanceForm");
					this.OnTAdvanceFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoApprove", DbType="Bit")]
		public System.Nullable<bool> AutoApprove
		{
			get
			{
				return this._AutoApprove;
			}
			set
			{
				if ((this._AutoApprove != value))
				{
					this.OnAutoApproveChanging(value);
					this.SendPropertyChanging();
					this._AutoApprove = value;
					this.SendPropertyChanged("AutoApprove");
					this.OnAutoApproveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoApproveWhen", DbType="NVarChar(2)")]
		public string AutoApproveWhen
		{
			get
			{
				return this._AutoApproveWhen;
			}
			set
			{
				if ((this._AutoApproveWhen != value))
				{
					this.OnAutoApproveWhenChanging(value);
					this.SendPropertyChanging();
					this._AutoApproveWhen = value;
					this.SendPropertyChanged("AutoApproveWhen");
					this.OnAutoApproveWhenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApproverCanEdit", DbType="Bit")]
		public System.Nullable<bool> ApproverCanEdit
		{
			get
			{
				return this._ApproverCanEdit;
			}
			set
			{
				if ((this._ApproverCanEdit != value))
				{
					this.OnApproverCanEditChanging(value);
					this.SendPropertyChanging();
					this._ApproverCanEdit = value;
					this.SendPropertyChanged("ApproverCanEdit");
					this.OnApproverCanEditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorId", DbType="Int")]
		public System.Nullable<int> CreatorId
		{
			get
			{
				return this._CreatorId;
			}
			set
			{
				if ((this._CreatorId != value))
				{
					this.OnCreatorIdChanging(value);
					this.SendPropertyChanging();
					this._CreatorId = value;
					this.SendPropertyChanged("CreatorId");
					this.OnCreatorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNameTh", DbType="NVarChar(500)")]
		public string CNameTh
		{
			get
			{
				return this._CNameTh;
			}
			set
			{
				if ((this._CNameTh != value))
				{
					this.OnCNameThChanging(value);
					this.SendPropertyChanging();
					this._CNameTh = value;
					this.SendPropertyChanged("CNameTh");
					this.OnCNameThChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNameEn", DbType="NVarChar(500)")]
		public string CNameEn
		{
			get
			{
				return this._CNameEn;
			}
			set
			{
				if ((this._CNameEn != value))
				{
					this.OnCNameEnChanging(value);
					this.SendPropertyChanging();
					this._CNameEn = value;
					this.SendPropertyChanged("CNameEn");
					this.OnCNameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPositionId", DbType="Int")]
		public System.Nullable<int> CPositionId
		{
			get
			{
				return this._CPositionId;
			}
			set
			{
				if ((this._CPositionId != value))
				{
					this.OnCPositionIdChanging(value);
					this.SendPropertyChanging();
					this._CPositionId = value;
					this.SendPropertyChanged("CPositionId");
					this.OnCPositionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPositionTh", DbType="NVarChar(500)")]
		public string CPositionTh
		{
			get
			{
				return this._CPositionTh;
			}
			set
			{
				if ((this._CPositionTh != value))
				{
					this.OnCPositionThChanging(value);
					this.SendPropertyChanging();
					this._CPositionTh = value;
					this.SendPropertyChanged("CPositionTh");
					this.OnCPositionThChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPositionEn", DbType="NVarChar(500)")]
		public string CPositionEn
		{
			get
			{
				return this._CPositionEn;
			}
			set
			{
				if ((this._CPositionEn != value))
				{
					this.OnCPositionEnChanging(value);
					this.SendPropertyChanging();
					this._CPositionEn = value;
					this.SendPropertyChanged("CPositionEn");
					this.OnCPositionEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDepartmentId", DbType="Int")]
		public System.Nullable<int> CDepartmentId
		{
			get
			{
				return this._CDepartmentId;
			}
			set
			{
				if ((this._CDepartmentId != value))
				{
					this.OnCDepartmentIdChanging(value);
					this.SendPropertyChanging();
					this._CDepartmentId = value;
					this.SendPropertyChanged("CDepartmentId");
					this.OnCDepartmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDepartmentTh", DbType="NVarChar(500)")]
		public string CDepartmentTh
		{
			get
			{
				return this._CDepartmentTh;
			}
			set
			{
				if ((this._CDepartmentTh != value))
				{
					this.OnCDepartmentThChanging(value);
					this.SendPropertyChanging();
					this._CDepartmentTh = value;
					this.SendPropertyChanged("CDepartmentTh");
					this.OnCDepartmentThChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDepartmentEn", DbType="NVarChar(500)")]
		public string CDepartmentEn
		{
			get
			{
				return this._CDepartmentEn;
			}
			set
			{
				if ((this._CDepartmentEn != value))
				{
					this.OnCDepartmentEnChanging(value);
					this.SendPropertyChanging();
					this._CDepartmentEn = value;
					this.SendPropertyChanged("CDepartmentEn");
					this.OnCDepartmentEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDivisionId", DbType="Int")]
		public System.Nullable<int> CDivisionId
		{
			get
			{
				return this._CDivisionId;
			}
			set
			{
				if ((this._CDivisionId != value))
				{
					this.OnCDivisionIdChanging(value);
					this.SendPropertyChanging();
					this._CDivisionId = value;
					this.SendPropertyChanged("CDivisionId");
					this.OnCDivisionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDivisionTh", DbType="NVarChar(500)")]
		public string CDivisionTh
		{
			get
			{
				return this._CDivisionTh;
			}
			set
			{
				if ((this._CDivisionTh != value))
				{
					this.OnCDivisionThChanging(value);
					this.SendPropertyChanging();
					this._CDivisionTh = value;
					this.SendPropertyChanged("CDivisionTh");
					this.OnCDivisionThChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDivisionEn", DbType="NVarChar(500)")]
		public string CDivisionEn
		{
			get
			{
				return this._CDivisionEn;
			}
			set
			{
				if ((this._CDivisionEn != value))
				{
					this.OnCDivisionEnChanging(value);
					this.SendPropertyChanging();
					this._CDivisionEn = value;
					this.SendPropertyChanged("CDivisionEn");
					this.OnCDivisionEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequesterId", DbType="Int")]
		public System.Nullable<int> RequesterId
		{
			get
			{
				return this._RequesterId;
			}
			set
			{
				if ((this._RequesterId != value))
				{
					this.OnRequesterIdChanging(value);
					this.SendPropertyChanging();
					this._RequesterId = value;
					this.SendPropertyChanged("RequesterId");
					this.OnRequesterIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNameTh", DbType="NVarChar(500)")]
		public string RNameTh
		{
			get
			{
				return this._RNameTh;
			}
			set
			{
				if ((this._RNameTh != value))
				{
					this.OnRNameThChanging(value);
					this.SendPropertyChanging();
					this._RNameTh = value;
					this.SendPropertyChanged("RNameTh");
					this.OnRNameThChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNameEn", DbType="NVarChar(500)")]
		public string RNameEn
		{
			get
			{
				return this._RNameEn;
			}
			set
			{
				if ((this._RNameEn != value))
				{
					this.OnRNameEnChanging(value);
					this.SendPropertyChanging();
					this._RNameEn = value;
					this.SendPropertyChanged("RNameEn");
					this.OnRNameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPositionId", DbType="Int")]
		public System.Nullable<int> RPositionId
		{
			get
			{
				return this._RPositionId;
			}
			set
			{
				if ((this._RPositionId != value))
				{
					this.OnRPositionIdChanging(value);
					this.SendPropertyChanging();
					this._RPositionId = value;
					this.SendPropertyChanged("RPositionId");
					this.OnRPositionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPositionTh", DbType="NVarChar(500)")]
		public string RPositionTh
		{
			get
			{
				return this._RPositionTh;
			}
			set
			{
				if ((this._RPositionTh != value))
				{
					this.OnRPositionThChanging(value);
					this.SendPropertyChanging();
					this._RPositionTh = value;
					this.SendPropertyChanged("RPositionTh");
					this.OnRPositionThChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPositionEn", DbType="NVarChar(500)")]
		public string RPositionEn
		{
			get
			{
				return this._RPositionEn;
			}
			set
			{
				if ((this._RPositionEn != value))
				{
					this.OnRPositionEnChanging(value);
					this.SendPropertyChanging();
					this._RPositionEn = value;
					this.SendPropertyChanged("RPositionEn");
					this.OnRPositionEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDepartmentId", DbType="Int")]
		public System.Nullable<int> RDepartmentId
		{
			get
			{
				return this._RDepartmentId;
			}
			set
			{
				if ((this._RDepartmentId != value))
				{
					this.OnRDepartmentIdChanging(value);
					this.SendPropertyChanging();
					this._RDepartmentId = value;
					this.SendPropertyChanged("RDepartmentId");
					this.OnRDepartmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDepartmentTh", DbType="NVarChar(500)")]
		public string RDepartmentTh
		{
			get
			{
				return this._RDepartmentTh;
			}
			set
			{
				if ((this._RDepartmentTh != value))
				{
					this.OnRDepartmentThChanging(value);
					this.SendPropertyChanging();
					this._RDepartmentTh = value;
					this.SendPropertyChanged("RDepartmentTh");
					this.OnRDepartmentThChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDepartmentEn", DbType="NVarChar(500)")]
		public string RDepartmentEn
		{
			get
			{
				return this._RDepartmentEn;
			}
			set
			{
				if ((this._RDepartmentEn != value))
				{
					this.OnRDepartmentEnChanging(value);
					this.SendPropertyChanging();
					this._RDepartmentEn = value;
					this.SendPropertyChanged("RDepartmentEn");
					this.OnRDepartmentEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDivisionId", DbType="Int")]
		public System.Nullable<int> RDivisionId
		{
			get
			{
				return this._RDivisionId;
			}
			set
			{
				if ((this._RDivisionId != value))
				{
					this.OnRDivisionIdChanging(value);
					this.SendPropertyChanging();
					this._RDivisionId = value;
					this.SendPropertyChanged("RDivisionId");
					this.OnRDivisionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDivisionTh", DbType="NVarChar(500)")]
		public string RDivisionTh
		{
			get
			{
				return this._RDivisionTh;
			}
			set
			{
				if ((this._RDivisionTh != value))
				{
					this.OnRDivisionThChanging(value);
					this.SendPropertyChanging();
					this._RDivisionTh = value;
					this.SendPropertyChanged("RDivisionTh");
					this.OnRDivisionThChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDivisionEn", DbType="NVarChar(500)")]
		public string RDivisionEn
		{
			get
			{
				return this._RDivisionEn;
			}
			set
			{
				if ((this._RDivisionEn != value))
				{
					this.OnRDivisionEnChanging(value);
					this.SendPropertyChanging();
					this._RDivisionEn = value;
					this.SendPropertyChanged("RDivisionEn");
					this.OnRDivisionEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemoSubject", DbType="NVarChar(500)")]
		public string MemoSubject
		{
			get
			{
				return this._MemoSubject;
			}
			set
			{
				if ((this._MemoSubject != value))
				{
					this.OnMemoSubjectChanging(value);
					this.SendPropertyChanging();
					this._MemoSubject = value;
					this.SendPropertyChanged("MemoSubject");
					this.OnMemoSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MTextForm", DbType="NVarChar(MAX)")]
		public string MTextForm
		{
			get
			{
				return this._MTextForm;
			}
			set
			{
				if ((this._MTextForm != value))
				{
					this.OnMTextFormChanging(value);
					this.SendPropertyChanging();
					this._MTextForm = value;
					this.SendPropertyChanged("MTextForm");
					this.OnMTextFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAdvancveForm", DbType="NVarChar(MAX)")]
		public string MAdvancveForm
		{
			get
			{
				return this._MAdvancveForm;
			}
			set
			{
				if ((this._MAdvancveForm != value))
				{
					this.OnMAdvancveFormChanging(value);
					this.SendPropertyChanging();
					this._MAdvancveForm = value;
					this.SendPropertyChanged("MAdvancveForm");
					this.OnMAdvancveFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusId", DbType="Int")]
		public System.Nullable<int> StatusId
		{
			get
			{
				return this._StatusId;
			}
			set
			{
				if ((this._StatusId != value))
				{
					this.OnStatusIdChanging(value);
					this.SendPropertyChanging();
					this._StatusId = value;
					this.SendPropertyChanged("StatusId");
					this.OnStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusName", DbType="NVarChar(500)")]
		public string StatusName
		{
			get
			{
				return this._StatusName;
			}
			set
			{
				if ((this._StatusName != value))
				{
					this.OnStatusNameChanging(value);
					this.SendPropertyChanging();
					this._StatusName = value;
					this.SendPropertyChanged("StatusName");
					this.OnStatusNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentApprovalLevel", DbType="Int")]
		public System.Nullable<int> CurrentApprovalLevel
		{
			get
			{
				return this._CurrentApprovalLevel;
			}
			set
			{
				if ((this._CurrentApprovalLevel != value))
				{
					this.OnCurrentApprovalLevelChanging(value);
					this.SendPropertyChanging();
					this._CurrentApprovalLevel = value;
					this.SendPropertyChanged("CurrentApprovalLevel");
					this.OnCurrentApprovalLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RequestDate
		{
			get
			{
				return this._RequestDate;
			}
			set
			{
				if ((this._RequestDate != value))
				{
					this.OnRequestDateChanging(value);
					this.SendPropertyChanging();
					this._RequestDate = value;
					this.SendPropertyChanged("RequestDate");
					this.OnRequestDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(500)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(500)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActionBy", DbType="NVarChar(500)")]
		public string LastActionBy
		{
			get
			{
				return this._LastActionBy;
			}
			set
			{
				if ((this._LastActionBy != value))
				{
					this.OnLastActionByChanging(value);
					this.SendPropertyChanging();
					this._LastActionBy = value;
					this.SendPropertyChanged("LastActionBy");
					this.OnLastActionByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastStatusId", DbType="Int")]
		public System.Nullable<int> LastStatusId
		{
			get
			{
				return this._LastStatusId;
			}
			set
			{
				if ((this._LastStatusId != value))
				{
					this.OnLastStatusIdChanging(value);
					this.SendPropertyChanging();
					this._LastStatusId = value;
					this.SendPropertyChanged("LastStatusId");
					this.OnLastStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastStatusName", DbType="NVarChar(500)")]
		public string LastStatusName
		{
			get
			{
				return this._LastStatusName;
			}
			set
			{
				if ((this._LastStatusName != value))
				{
					this.OnLastStatusNameChanging(value);
					this.SendPropertyChanging();
					this._LastStatusName = value;
					this.SendPropertyChanged("LastStatusName");
					this.OnLastStatusNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonWaitingId", DbType="Int")]
		public System.Nullable<int> PersonWaitingId
		{
			get
			{
				return this._PersonWaitingId;
			}
			set
			{
				if ((this._PersonWaitingId != value))
				{
					this.OnPersonWaitingIdChanging(value);
					this.SendPropertyChanging();
					this._PersonWaitingId = value;
					this.SendPropertyChanged("PersonWaitingId");
					this.OnPersonWaitingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonWaiting", DbType="NVarChar(500)")]
		public string PersonWaiting
		{
			get
			{
				return this._PersonWaiting;
			}
			set
			{
				if ((this._PersonWaiting != value))
				{
					this.OnPersonWaitingChanging(value);
					this.SendPropertyChanging();
					this._PersonWaiting = value;
					this.SendPropertyChanged("PersonWaiting");
					this.OnPersonWaitingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int")]
		public System.Nullable<int> AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="Int")]
		public System.Nullable<int> CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this.OnCompanyIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyId = value;
					this.SendPropertyChanged("CompanyId");
					this.OnCompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(400)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectID", DbType="Int")]
		public System.Nullable<int> ProjectID
		{
			get
			{
				return this._ProjectID;
			}
			set
			{
				if ((this._ProjectID != value))
				{
					this.OnProjectIDChanging(value);
					this.SendPropertyChanging();
					this._ProjectID = value;
					this.SendPropertyChanged("ProjectID");
					this.OnProjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectName", DbType="NVarChar(400)")]
		public string ProjectName
		{
			get
			{
				return this._ProjectName;
			}
			set
			{
				if ((this._ProjectName != value))
				{
					this.OnProjectNameChanging(value);
					this.SendPropertyChanging();
					this._ProjectName = value;
					this.SendPropertyChanged("ProjectName");
					this.OnProjectNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReaded", DbType="Bit NOT NULL")]
		public bool IsReaded
		{
			get
			{
				return this._IsReaded;
			}
			set
			{
				if ((this._IsReaded != value))
				{
					this.OnIsReadedChanging(value);
					this.SendPropertyChanging();
					this._IsReaded = value;
					this.SendPropertyChanged("IsReaded");
					this.OnIsReadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateApproveId", DbType="NVarChar(10)")]
		public string TemplateApproveId
		{
			get
			{
				return this._TemplateApproveId;
			}
			set
			{
				if ((this._TemplateApproveId != value))
				{
					this.OnTemplateApproveIdChanging(value);
					this.SendPropertyChanging();
					this._TemplateApproveId = value;
					this.SendPropertyChanged("TemplateApproveId");
					this.OnTemplateApproveIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckEmpID", DbType="Int")]
		public System.Nullable<int> CheckEmpID
		{
			get
			{
				return this._CheckEmpID;
			}
			set
			{
				if ((this._CheckEmpID != value))
				{
					this.OnCheckEmpIDChanging(value);
					this.SendPropertyChanging();
					this._CheckEmpID = value;
					this.SendPropertyChanged("CheckEmpID");
					this.OnCheckEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLAStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SLAStartDate
		{
			get
			{
				return this._SLAStartDate;
			}
			set
			{
				if ((this._SLAStartDate != value))
				{
					this.OnSLAStartDateChanging(value);
					this.SendPropertyChanging();
					this._SLAStartDate = value;
					this.SendPropertyChanged("SLAStartDate");
					this.OnSLAStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLACompletedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SLACompletedDate
		{
			get
			{
				return this._SLACompletedDate;
			}
			set
			{
				if ((this._SLACompletedDate != value))
				{
					this.OnSLACompletedDateChanging(value);
					this.SendPropertyChanging();
					this._SLACompletedDate = value;
					this.SendPropertyChanged("SLACompletedDate");
					this.OnSLACompletedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CompletedDate
		{
			get
			{
				return this._CompletedDate;
			}
			set
			{
				if ((this._CompletedDate != value))
				{
					this.OnCompletedDateChanging(value);
					this.SendPropertyChanging();
					this._CompletedDate = value;
					this.SendPropertyChanged("CompletedDate");
					this.OnCompletedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsProcess", DbType="Bit")]
		public System.Nullable<bool> IsProcess
		{
			get
			{
				return this._IsProcess;
			}
			set
			{
				if ((this._IsProcess != value))
				{
					this.OnIsProcessChanging(value);
					this.SendPropertyChanging();
					this._IsProcess = value;
					this.SendPropertyChanged("IsProcess");
					this.OnIsProcessChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MSTTemplate")]
	public partial class MSTTemplate
	{
		
		private int _TemplateId;
		
		private string _GroupTemplateName;
		
		private string _TemplateName;
		
		private System.Nullable<int> _DepartmentId;
		
		private string _DocumentCode;
		
		private System.Nullable<bool> _isPublic;
		
		private string _ReportLang;
		
		private string _TemplateDetail;
		
		private string _ToId;
		
		private string _CcId;
		
		private string _TemplateSubject;
		
		private System.Nullable<bool> _IsTextForm;
		
		private string _TextForm;
		
		private string _AdvanceForm;
		
		private System.Nullable<bool> _AutoApprove;
		
		private string _AutoApproveWhen;
		
		private System.Nullable<bool> _ApproverCanEdit;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private string _ModifiedBy;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsEdit;
		
		private System.Nullable<bool> _IsDelete;
		
		private System.Nullable<int> _AccountId;
		
		private System.Nullable<bool> _isPDFShowInfo;
		
		private System.Nullable<bool> _isRequesterEditApproval;
		
		private System.Nullable<bool> _isFormControl;
		
		private string _RoleID;
		
		private string _SpecificEmployeeId;
		
		private string _SpecificRoleId;
		
		private string _RefTemplate;
		
		private string _MultiDeptId;
		
		private System.Nullable<bool> _ReqAttach;
		
		private string _RefDocColumn;
		
		private string _RefDocDisplay;
		
		private System.Nullable<bool> _IsCheckAccess;
		
		private System.Nullable<bool> _IsDefaultLineApprove;
		
		private bool _RequiredAttachment;
		
		public MSTTemplate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					this._TemplateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupTemplateName", DbType="NVarChar(500)")]
		public string GroupTemplateName
		{
			get
			{
				return this._GroupTemplateName;
			}
			set
			{
				if ((this._GroupTemplateName != value))
				{
					this._GroupTemplateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateName", DbType="NVarChar(500)")]
		public string TemplateName
		{
			get
			{
				return this._TemplateName;
			}
			set
			{
				if ((this._TemplateName != value))
				{
					this._TemplateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="Int")]
		public System.Nullable<int> DepartmentId
		{
			get
			{
				return this._DepartmentId;
			}
			set
			{
				if ((this._DepartmentId != value))
				{
					this._DepartmentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentCode", DbType="NVarChar(50)")]
		public string DocumentCode
		{
			get
			{
				return this._DocumentCode;
			}
			set
			{
				if ((this._DocumentCode != value))
				{
					this._DocumentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPublic", DbType="Bit")]
		public System.Nullable<bool> isPublic
		{
			get
			{
				return this._isPublic;
			}
			set
			{
				if ((this._isPublic != value))
				{
					this._isPublic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportLang", DbType="NVarChar(2)")]
		public string ReportLang
		{
			get
			{
				return this._ReportLang;
			}
			set
			{
				if ((this._ReportLang != value))
				{
					this._ReportLang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateDetail", DbType="NVarChar(500)")]
		public string TemplateDetail
		{
			get
			{
				return this._TemplateDetail;
			}
			set
			{
				if ((this._TemplateDetail != value))
				{
					this._TemplateDetail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToId", DbType="NVarChar(500)")]
		public string ToId
		{
			get
			{
				return this._ToId;
			}
			set
			{
				if ((this._ToId != value))
				{
					this._ToId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CcId", DbType="NVarChar(500)")]
		public string CcId
		{
			get
			{
				return this._CcId;
			}
			set
			{
				if ((this._CcId != value))
				{
					this._CcId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateSubject", DbType="NVarChar(500)")]
		public string TemplateSubject
		{
			get
			{
				return this._TemplateSubject;
			}
			set
			{
				if ((this._TemplateSubject != value))
				{
					this._TemplateSubject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTextForm", DbType="Bit")]
		public System.Nullable<bool> IsTextForm
		{
			get
			{
				return this._IsTextForm;
			}
			set
			{
				if ((this._IsTextForm != value))
				{
					this._IsTextForm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextForm", DbType="NVarChar(MAX)")]
		public string TextForm
		{
			get
			{
				return this._TextForm;
			}
			set
			{
				if ((this._TextForm != value))
				{
					this._TextForm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceForm", DbType="NVarChar(MAX)")]
		public string AdvanceForm
		{
			get
			{
				return this._AdvanceForm;
			}
			set
			{
				if ((this._AdvanceForm != value))
				{
					this._AdvanceForm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoApprove", DbType="Bit")]
		public System.Nullable<bool> AutoApprove
		{
			get
			{
				return this._AutoApprove;
			}
			set
			{
				if ((this._AutoApprove != value))
				{
					this._AutoApprove = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoApproveWhen", DbType="NVarChar(2)")]
		public string AutoApproveWhen
		{
			get
			{
				return this._AutoApproveWhen;
			}
			set
			{
				if ((this._AutoApproveWhen != value))
				{
					this._AutoApproveWhen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApproverCanEdit", DbType="Bit")]
		public System.Nullable<bool> ApproverCanEdit
		{
			get
			{
				return this._ApproverCanEdit;
			}
			set
			{
				if ((this._ApproverCanEdit != value))
				{
					this._ApproverCanEdit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(500)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(500)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEdit", DbType="Bit")]
		public System.Nullable<bool> IsEdit
		{
			get
			{
				return this._IsEdit;
			}
			set
			{
				if ((this._IsEdit != value))
				{
					this._IsEdit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit")]
		public System.Nullable<bool> IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int")]
		public System.Nullable<int> AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this._AccountId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPDFShowInfo", DbType="Bit")]
		public System.Nullable<bool> isPDFShowInfo
		{
			get
			{
				return this._isPDFShowInfo;
			}
			set
			{
				if ((this._isPDFShowInfo != value))
				{
					this._isPDFShowInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isRequesterEditApproval", DbType="Bit")]
		public System.Nullable<bool> isRequesterEditApproval
		{
			get
			{
				return this._isRequesterEditApproval;
			}
			set
			{
				if ((this._isRequesterEditApproval != value))
				{
					this._isRequesterEditApproval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFormControl", DbType="Bit")]
		public System.Nullable<bool> isFormControl
		{
			get
			{
				return this._isFormControl;
			}
			set
			{
				if ((this._isFormControl != value))
				{
					this._isFormControl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="NVarChar(MAX)")]
		public string RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecificEmployeeId", DbType="NVarChar(MAX)")]
		public string SpecificEmployeeId
		{
			get
			{
				return this._SpecificEmployeeId;
			}
			set
			{
				if ((this._SpecificEmployeeId != value))
				{
					this._SpecificEmployeeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecificRoleId", DbType="NVarChar(MAX)")]
		public string SpecificRoleId
		{
			get
			{
				return this._SpecificRoleId;
			}
			set
			{
				if ((this._SpecificRoleId != value))
				{
					this._SpecificRoleId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefTemplate", DbType="NVarChar(MAX)")]
		public string RefTemplate
		{
			get
			{
				return this._RefTemplate;
			}
			set
			{
				if ((this._RefTemplate != value))
				{
					this._RefTemplate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MultiDeptId", DbType="NVarChar(MAX)")]
		public string MultiDeptId
		{
			get
			{
				return this._MultiDeptId;
			}
			set
			{
				if ((this._MultiDeptId != value))
				{
					this._MultiDeptId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReqAttach", DbType="Bit")]
		public System.Nullable<bool> ReqAttach
		{
			get
			{
				return this._ReqAttach;
			}
			set
			{
				if ((this._ReqAttach != value))
				{
					this._ReqAttach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefDocColumn", DbType="NVarChar(MAX)")]
		public string RefDocColumn
		{
			get
			{
				return this._RefDocColumn;
			}
			set
			{
				if ((this._RefDocColumn != value))
				{
					this._RefDocColumn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefDocDisplay", DbType="NVarChar(MAX)")]
		public string RefDocDisplay
		{
			get
			{
				return this._RefDocDisplay;
			}
			set
			{
				if ((this._RefDocDisplay != value))
				{
					this._RefDocDisplay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCheckAccess", DbType="Bit")]
		public System.Nullable<bool> IsCheckAccess
		{
			get
			{
				return this._IsCheckAccess;
			}
			set
			{
				if ((this._IsCheckAccess != value))
				{
					this._IsCheckAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefaultLineApprove", DbType="Bit")]
		public System.Nullable<bool> IsDefaultLineApprove
		{
			get
			{
				return this._IsDefaultLineApprove;
			}
			set
			{
				if ((this._IsDefaultLineApprove != value))
				{
					this._IsDefaultLineApprove = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiredAttachment", DbType="Bit NOT NULL")]
		public bool RequiredAttachment
		{
			get
			{
				return this._RequiredAttachment;
			}
			set
			{
				if ((this._RequiredAttachment != value))
				{
					this._RequiredAttachment = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
